---
- include: Debian.yml
  when: ansible_os_family == "Debian"

- name: Add project working user
  user: 
    name: "{{ruby_app_user}}"
    home: "/home/{{ruby_app_user}}"
    shell: "/bin/bash"

- name: Update home permissions
  file:
    path: "/home/{{ruby_app_user}}"
    mode: 0750
    owner: "{{ruby_app_user}}"
    group: "{{ruby_app_user}}"
    state: directory

- name: Create app directories
  file:
    path: "/home/{{ ruby_app_user +'/'+ ruby_app_name + '/' +  item }}"
    mode: 0750
    owner: "{{ruby_app_user}}"
    group: "{{ruby_app_user}}"
    state: directory
  with_items:
    - ./
    - releases
    - shared
    - repo
    - shared/bin
    - shared/config
    - shared/config/settings
    - shared/log
    - shared/tmp
    - shared/tmp/pids
    - shared/tmp/cache
    - shared/tmp/sockets
    - shared/vendor
    - shared/vendor/bundle
    - shared/public
    - shared/public/system

- name: Create additional app directories
  file:
    path: "/home/{{ ruby_app_user+'/'+ruby_app_name + '/' +  item }}"
    mode: 0750
    owner: "{{ruby_app_user}}"
    group: "{{ruby_app_user}}"
    state: directory
  with_items: ruby_app_additional_directories
  when: ruby_app_additional_directories is defined

- name: Create database.yml
  template:
    src: "database.yml.j2"
    dest: "/home/{{ ruby_app_user+'/'+ruby_app_name }}/shared/config/database.yml"
    owner: "{{ ruby_app_user }}"
    group: "{{ ruby_app_user }}"
  when: ruby_app_config_database is defined
  tags: ruby_install_database_yml
  notify:
    - service unicorn upgrade

- name: Create omniauth.yml
  template:
    src: "settings/omniauth.yml.j2"
    dest: "/home/{{ ruby_app_user+'/'+ruby_app_name }}/shared/config/omniauth.yml"
    owner: "{{ ruby_app_user }}"
    group: "{{ ruby_app_user }}"
  when: ruby_app_config_settings_omniauth is defined
  tags: ruby_install_omniauth_yml
  notify:
    - service unicorn upgrade

- name: Create secrets.yml
  template:
    src: "secrets.yml.j2"
    dest: "/home/{{ ruby_app_user+'/'+ruby_app_name }}/shared/config/secrets.yml"
    owner: "{{ ruby_app_user }}"
    group: "{{ ruby_app_user }}"
  when: ruby_app_config_secrets is defined
  tags: ruby_install_secrets_yml
  notify:
    - service unicorn upgrade

- name: Create sidekiq.yml
  template:
    src: "sidekiq.yml.j2"
    dest: "/home/{{ ruby_app_user+'/'+ruby_app_name }}/shared/config/sidekiq.yml"
    owner: "{{ ruby_app_user }}"
    group: "{{ ruby_app_user }}"
  when: ruby_app_config_sidekiq is defined
  tags: ruby_install_sidekiq_yml
  notify:
    - service unicorn upgrade

- name: Create unicorn.yml.j2
  template:
    src: "unicorn.yml.j2"
    dest: "/home/{{ ruby_app_user+'/'+ruby_app_name }}/shared/config/unicorn.yml"
    owner: "{{ ruby_app_user }}"
    group: "{{ ruby_app_user }}"
  when: ruby_app_enable_unicorn is defined
  tags: ruby_install_unicorn_yml
  notify:
    - service unicorn upgrade

- name: Create chewy.yml
  template:
    src: "chewy.yml.j2"
    dest: "/home/{{ ruby_app_user+'/'+ruby_app_name }}/shared/config/chewy.yml"
    owner: "{{ ruby_app_user }}"
    group: "{{ ruby_app_user }}"
  when: ruby_app_config_chewy is defined
  tags: ruby_install_chewy_yml
  notify:
    - service unicorn upgrade

- name: install logrotate.conf
  template:
    src: etc/logrotate.d/ruby.conf.j2
    dest: "/etc/logrotate.d/{{ ruby_app_name }}"
    owner: root
    group: root
    mode: 0644
  when: ruby_app_enable_unicorn is defined
